### ISSUE TITLE
Craig says the app isn't recognizing he paid dues?

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/swissmem-dapp#245]
![Screen Shot 2021-04-17 at 12.40.15 PM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/763b89b7-6b79-45c2-a765-165ad017b0dd)

https://etherscan.io/tx/0xf1239297a52da4998420b8c50cde22387fa1ec9dd674a24bf7282d39a688ea1a

He paid dues in that tx with 0x536c7e8f18d09d04697e0d2624b44bba575388c2

**Comment by GriffGreen** [comment]
https://blockscout.com/poa/xdai/address/0x536c7E8F18D09d04697E0d2624b44bBA575388c2/token-transfers 

It looks like he wasnt minted CSTK for his dues!

He was minted 1255 CSTK on feb 11th here: https://blockscout.com/xdai/mainnet/tx/0x5defba4323122902ca4cc69773d73c3eedb88b2bb2c941d810b785eb8cc2e2fe

But that is 6 days before he paid dues.

the next time he was minted was March 11th here:
https://blockscout.com/xdai/mainnet/tx/0xab8747839b26adeff871e547ab4ceb21d1c00725a017a7b214b7c88093f58410

We owe him 1125 CSTK

**Comment by cranders1** [comment]
Crooks! hahahah
thnx for tracking down so fast @GriffGreen 
perhaps my pestering will help out this time.

**Comment by aminlatifi** [comment]
Bridge had created a transaction on XDAI with hash `0x771777c9afb31415eeaba3cf0cca0d218a264d5035a7bc840fdffb809d2eaf48`, but there is no footprint of it on XDAI!

The promising point is that bridge has not ignored it :)
It's the log

```
2021-04-21 17:50: error: Failed to fetch tx receipt for tx {
  "txHash": "0x771777c9afb31415eeaba3cf0cca0d218a264d5035a7bc840fdffb809d2eaf48",
  "toHomeBridge": false,
  "status": "pending",
  "homeTx": "0xf1239297a52da4998420b8c50cde22387fa1ec9dd674a24bf7282d39a688ea1a",
  "receiverId": "2349",
  "token": "0x6B175474E89094C44Da98b954EedeAC495271d0F",
  "amount": "450000000000000000000",
  "sender": "0x536c7E8F18D09d04697E0d2624b44bBA575388c2",
  "_id": "SenMvoVbLCbwQH1D"
} Error: Returned error: Block information is incomplete while ancient block sync is still in progress, before it's finished we can't determine the existence of requested item.
    at Object.ErrorResponse (/home/deploy/giveth-bridge-cstoken/node_modules/web3-core-helpers/lib/errors.js:28:19)
    at /home/deploy/giveth-bridge-cstoken/node_modules/web3-core-requestmanager/lib/index.js:303:36
    at XMLHttpRequest.request.onreadystatechange (/home/deploy/giveth-bridge-cstoken/node_modules/web3-providers-http/lib/index.js:98:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/deploy/giveth-bridge-cstoken/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/home/deploy/giveth-bridge-cstoken/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/home/deploy/giveth-bridge-cstoken/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/home/deploy/giveth-bridge-cstoken/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2021-04-21 17:50: error: Failed to fetch tx receipt for tx {
  "toHomeBridge": false,
  "status": "pending",
  "homeTx": "0x0c447fb23167cfc4fa609d4b7d3b5fe0ac5a7ab0d1e3bdc70bf3c9ee954b3dda",
  "receiverId": "2349",
  "token": "0x6B175474E89094C44Da98b954EedeAC495271d0F",
  "amount": "455500000000000000000",
  "sender": "0x7d547666209755FB833f9B37EebEa38eBF513Abb",
  "_id": "gNHBsirlp2TvcZ64",
  "error": {
    "data": null
  },
  "reSend": true
} Error: Returned error: Invalid params
    at Object.ErrorResponse (/home/deploy/giveth-bridge-cstoken/node_modules/web3-core-helpers/lib/errors.js:28:19)
    at /home/deploy/giveth-bridge-cstoken/node_modules/web3-core-requestmanager/lib/index.js:303:36
    at XMLHttpRequest.request.onreadystatechange (/home/deploy/giveth-bridge-cstoken/node_modules/web3-providers-http/lib/index.js:98:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/deploy/giveth-bridge-cstoken/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/home/deploy/giveth-bridge-cstoken/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/home/deploy/giveth-bridge-cstoken/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/home/deploy/giveth-bridge-cstoken/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

```

So he is not alone, we owe 0x7d547666209755fb833f9b37eebea38ebf513abb (Juan Carlos Bell Llinás) probably too.

**Comment by JuankBell** [comment]
Thanks!

**Comment by GriffGreen** [comment]
Craig got his tokens!

**Comment by cranders1** [comment]
indeed. thnx @aminlatifi @GriffGreen for sleuthing.
